bot_host: http://localhost:12345
bot_authKey: superSecretAuthKey
bot_account: 12345678

server_properties:
  vanilla:
    address: 127.0.0.1
    rcon_port: 25575
    rcon_password: super-secret
    main_port: 25565
    server2group:
      enable: true
      default_group: 11111111
      log_path: /path/to/log/file
    aka:
      - v

repeat:
  enable: true
  random: false
  reverse: false
  threshold: 3

group_properties:
  11111111:
    default_server: vanilla

private_properties:
  12345678:
    default_server: vanilla

default_server: vanilla

command_say_bindings:
  12345678:  b8c8679b-a0f2-468c-9b38-79d4b0f068ac

permissions:
  group:
    11111111:
      default:
        - '*.list'
        - 'vanilla.whitelist.list'
        - 'vanilla.banlist'
        - 'vanilla.say'
      admin:
        - 'vanilla.whitelist.*'
        - 'vanilla.restart'
        - 'vanilla.ban'
        - 'vanilla.unban'

    22222222:
      default:
        - '*.list'
        - 'vanilla.whitelist.list'
        - 'vanilla.banlist'
        - 'vanilla.say'
      admin:
        - 'vanilla.whitelist.*'
        - 'vanilla.restart'
        - 'vanilla.ban'
        - 'vanilla.unban'

  private:
    33333333:
      - '*'
